model:
  base_learning_rate: 1.0e-4 # set to target_lr by starting main.py with '--scale_lr False'
  cond_model: True
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    w: 0.

    scheduler_config: # 10000 warmup steps
      warm_up_steps: [10000]
      cycle_lengths: [10000000000000]
      f_start: [1.e-6]
      f_max: [1.]
      f_min: [ 1.]

    unet_config:
      image_size: 32
      in_channels: 4
      out_channels: 4
      model_channels: 256
      attention_resolutions: [4,2,1]   # 32, 16, 8, 4
      num_res_blocks: 2
      channel_mult: [1,2,4,4]  # 32, 16, 8, 4, 2
      num_heads: 8
      use_scale_shift_norm: True
      resblock_updown: True
      cond_model: True